"""add sku column to products

Revision ID: 061effe41dda
Revises: 5b66831d68eb
Create Date: 2025-12-03 11:58:19.475378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '061effe41dda'
down_revision: Union[str, Sequence[str], None] = '5b66831d68eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_products_minimal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_products_minimal_id'), 'canonical_products_minimal', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_products_minimal_sku'), 'canonical_products_minimal', ['sku'], unique=True)
    op.create_index(op.f('ix_canonical_products_minimal_slug'), 'canonical_products_minimal', ['slug'], unique=True)
    op.create_table('canonical_products_production',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=100), nullable=False),
    sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('subcategory_id', sa.Integer(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Boolean(), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.CheckConstraint('selling_price >= 0', name='check_selling_price_positive'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canonical_products_production_id'), 'canonical_products_production', ['id'], unique=False)
    op.create_index(op.f('ix_canonical_products_production_sku'), 'canonical_products_production', ['sku'], unique=True)
    op.create_index(op.f('ix_canonical_products_production_slug'), 'canonical_products_production', ['slug'], unique=True)
    op.add_column('canonical_products', sa.Column('vendor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'canonical_products', 'vendors', ['vendor_id'], ['id'])
    op.add_column('categories', sa.Column('category_name', sa.String(length=255), nullable=False))
    op.add_column('categories', sa.Column('status', sa.Enum('active', 'inactive', name='categorystatus'), nullable=False))
    op.add_column('categories', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('categories', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_constraint(op.f('categories_name_key'), 'categories', type_='unique')
    op.create_unique_constraint(None, 'categories', ['category_name'])
    op.drop_column('categories', 'description')
    op.drop_column('categories', 'name')
    op.add_column('products', sa.Column('seo_keywords', sa.JSON(), nullable=True))
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    # Set default value for null selling_price before making it NOT NULL
    op.execute("UPDATE products SET selling_price = 0.0 WHERE selling_price IS NULL")
    op.alter_column('products', 'selling_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'meta_description',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('products_vendor_id_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'subcategories', ['sub_category_id'], ['id'])
    op.create_foreign_key(None, 'products', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'products', 'vendors', ['vendor_id'], ['id'])
    op.drop_column('products', 'price')
    op.add_column('products', sa.Column('sku', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_vendor_id_fkey'), 'products', 'vendors', ['vendor_id'], ['id'], ondelete='SET NULL')
    op.alter_column('products', 'meta_description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('products', 'selling_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('products', 'seo_keywords')
    op.add_column('categories', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('categories', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'categories', type_='unique')
    op.create_unique_constraint(op.f('categories_name_key'), 'categories', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('categories', 'updated_at')
    op.drop_column('categories', 'created_at')
    op.drop_column('categories', 'status')
    op.drop_column('categories', 'category_name')
    op.drop_constraint(None, 'canonical_products', type_='foreignkey')
    op.drop_column('canonical_products', 'vendor_id')
    op.drop_index(op.f('ix_canonical_products_production_slug'), table_name='canonical_products_production')
    op.drop_index(op.f('ix_canonical_products_production_sku'), table_name='canonical_products_production')
    op.drop_index(op.f('ix_canonical_products_production_id'), table_name='canonical_products_production')
    op.drop_table('canonical_products_production')
    op.drop_index(op.f('ix_canonical_products_minimal_slug'), table_name='canonical_products_minimal')
    op.drop_index(op.f('ix_canonical_products_minimal_sku'), table_name='canonical_products_minimal')
    op.drop_index(op.f('ix_canonical_products_minimal_id'), table_name='canonical_products_minimal')
    op.drop_table('canonical_products_minimal')
    # ### end Alembic commands ###
