"""update category schema

Revision ID: 1de625ffc30d
Revises: 061effe41dda
Create Date: 2025-12-04 14:08:23.129142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1de625ffc30d'
down_revision: Union[str, Sequence[str], None] = '061effe41dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_canonical_products_production_slug'), table_name='canonical_products_production')
    op.create_index('ix_canonical_products_production_slug', 'canonical_products_production', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_canonical_products_production_slug', table_name='canonical_products_production')
    op.create_index(op.f('ix_canonical_products_production_slug'), 'canonical_products_production', ['slug'], unique=True)
    # ### end Alembic commands ###
